/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent1 {
    }
}
declare global {
    interface HTMLMyComponent1Element extends Components.MyComponent1, HTMLStencilElement {
    }
    var HTMLMyComponent1Element: {
        prototype: HTMLMyComponent1Element;
        new (): HTMLMyComponent1Element;
    };
    interface HTMLElementTagNameMap {
        "my-component1": HTMLMyComponent1Element;
    }
}
declare namespace LocalJSX {
    interface MyComponent1 {
    }
    interface IntrinsicElements {
        "my-component1": MyComponent1;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component1": LocalJSX.MyComponent1 & JSXBase.HTMLAttributes<HTMLMyComponent1Element>;
        }
    }
}
